// examples/nuxt-app/app.vue
<template>
  <main style="font-family:sans-serif;max-width:640px;margin:40px auto;padding:0 20px">
    <h1 style="margin-bottom:32px">Team Dashboard</h1>

    <!-- BUG 1: counter increments by 2 but logs +1 -->
    <section id="counter-section">
      <h2>Page Views</h2>
      <p>Total views: <strong id="view-count">{{ views }}</strong></p>
      <button id="record-view-btn" @click="recordView">Record View</button>
      <p style="color:#888;font-size:13px">Each click should add 1 view.</p>
    </section>

    <hr style="margin:32px 0">

    <!-- BUG 2: case-sensitive name search -->
    <section id="search-section">
      <h2>Team Directory</h2>
      <input
        id="search-input"
        v-model="query"
        type="text"
        placeholder="Search by name or department…"
        style="width:100%;padding:6px 8px;box-sizing:border-box;margin-bottom:12px"
        @input="onSearch"
      />
      <p id="result-count" style="color:#888;font-size:13px">
        {{ query ? `${filteredTeam.length} of ${team.length} members match` : `${team.length} members` }}
      </p>
      <ul id="member-list" style="list-style:none;padding:0;margin:0">
        <li
          v-for="m in filteredTeam"
          :key="m.id"
          :data-member-id="m.id"
          style="padding:6px 0;border-bottom:1px solid #eee"
        >
          <strong>{{ m.name }}</strong> — {{ m.department }}
        </li>
      </ul>
    </section>

    <hr style="margin:32px 0">

    <!-- BUG 3: fetch from /api/events (404), error swallowed -->
    <section id="feed-section">
      <h2>Activity Feed</h2>
      <button id="refresh-btn" :disabled="loading" @click="refreshFeed">
        {{ loading ? "Loading…" : "Refresh Feed" }}
      </button>
      <p id="feed-status" style="color:#888;font-size:13px;margin-top:8px">{{ feedStatus }}</p>
    </section>
  </main>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

const team = [
  { id: 1, name: "Alice Chen", department: "Platform" },
  { id: 2, name: "Bob Martinez", department: "Product" },
  { id: 3, name: "Carol Smith", department: "Platform" },
  { id: 4, name: "David Kim", department: "Product" },
  { id: 5, name: "Eve Johnson", department: "Data" },
  { id: 6, name: "Frank Lee", department: "Data" },
];

// Counter
const views = ref(0);
function recordView() {
  const next = views.value + 1;
  console.log("page view recorded, total:", next);
  views.value += 2; // BUG: off-by-one — should be += 1
}

// Search
const query = ref("");
const filteredTeam = computed(() =>
  team.filter(
    m =>
      m.name.includes(query.value) || // BUG: missing .toLowerCase() on m.name
      m.department.toLowerCase().includes(query.value.toLowerCase()),
  ),
);
function onSearch() {
  console.log("searching team for:", query.value);
}

// Feed
const loading = ref(false);
const feedStatus = ref("No events yet. Click Refresh.");
async function refreshFeed() {
  loading.value = true;
  console.log("refreshing activity feed...");
  try {
    // BUG: wrong URL — should be https://jsonplaceholder.typicode.com/posts?_limit=5
    const res = await fetch("/api/events");
    const data = await res.json();
    console.log("feed loaded,", data.length, "events");
    feedStatus.value = "";
  } catch (err) {
    // BUG: error swallowed — user sees nothing
    console.error("feed fetch failed:", err);
    feedStatus.value = "No events yet. Click Refresh.";
  } finally {
    loading.value = false;
  }
}
</script>

// examples/nextjs-app/app/page.tsx
"use client";
import { useState } from "react";

const TEAM = [
  { id: 1, name: "Alice Chen",   department: "Platform" },
  { id: 2, name: "Bob Martinez", department: "Product"  },
  { id: 3, name: "Carol Smith",  department: "Platform" },
  { id: 4, name: "David Kim",    department: "Product"  },
  { id: 5, name: "Eve Johnson",  department: "Data"     },
  { id: 6, name: "Frank Lee",    department: "Data"     },
];

export default function Page() {
  return (
    <main style={{ maxWidth: 640, margin: "40px auto", padding: "0 20px" }}>
      <h1 style={{ marginBottom: 32 }}>Team Dashboard</h1>
      <PageViewCounter />
      <hr style={{ margin: "32px 0" }} />
      <TeamSearch />
      <hr style={{ margin: "32px 0" }} />
      <ActivityFeed />
    </main>
  );
}

// BUG: increments state by 2 but logs +1
function PageViewCounter() {
  const [views, setViews] = useState(0);
  function recordView() {
    const next = views + 1;
    console.log("page view recorded, total:", next);
    setViews(views + 2);
  }
  return (
    <section id="counter-section">
      <h2>Page Views</h2>
      <p>Total views: <strong id="view-count">{views}</strong></p>
      <button id="record-view-btn" onClick={recordView}>Record View</button>
      <p style={{ color: "#888", fontSize: 13 }}>Each click should add 1 view.</p>
    </section>
  );
}

// BUG: case-sensitive name search
function TeamSearch() {
  const [query, setQuery] = useState("");
  const results = TEAM.filter(m =>
    m.name.includes(query) ||
    m.department.toLowerCase().includes(query.toLowerCase())
  );
  return (
    <section id="search-section">
      <h2>Team Directory</h2>
      <input
        id="search-input"
        type="text"
        placeholder="Search by name or department…"
        value={query}
        onChange={e => { console.log("searching team for:", e.target.value); setQuery(e.target.value); }}
        style={{ width: "100%", padding: "6px 8px", marginBottom: 12, boxSizing: "border-box" }}
      />
      <p id="result-count" style={{ color: "#888", fontSize: 13 }}>
        {query ? `${results.length} of ${TEAM.length} members match` : `${TEAM.length} members`}
      </p>
      <ul id="member-list" style={{ listStyle: "none", padding: 0, margin: 0 }}>
        {results.map(m => (
          <li key={m.id} data-member-id={m.id} style={{ padding: "6px 0", borderBottom: "1px solid #eee" }}>
            <strong>{m.name}</strong> — {m.department}
          </li>
        ))}
      </ul>
    </section>
  );
}

// BUG: fetches from /api/events (404), error swallowed
function ActivityFeed() {
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState("No events yet. Click Refresh.");
  async function refresh() {
    setLoading(true);
    console.log("refreshing activity feed...");
    try {
      const res = await fetch("/api/events");
      const data = await res.json();
      console.log("feed loaded,", data.length, "events");
      setStatus("");
    } catch (err) {
      console.error("feed fetch failed:", err);
      setStatus("No events yet. Click Refresh.");
    } finally {
      setLoading(false);
    }
  }
  return (
    <section id="feed-section">
      <h2>Activity Feed</h2>
      <button id="refresh-btn" onClick={refresh} disabled={loading}>
        {loading ? "Loading…" : "Refresh Feed"}
      </button>
      <p id="feed-status" style={{ color: "#888", fontSize: 13, marginTop: 8 }}>{status}</p>
    </section>
  );
}
